export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const GENERATE_OTP = "GENERATE_OTP";

export const COUNT_SHOPS = "COUNT_SHOPS";
export const SHOP_PFS = "SHOP_PFS";

export const GET_ALL_USERS = "GET_ALL_USERS";
export const DELETE_USER = "DELETE_USER";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const ADD_USER = "ADD_USER";

export const GET_ALL_SHOPS = "GET_ALL_SHOPS";
export const SHOP_OWNER_SHOPS = "SHOP_OWNER_SHOPS";
export const GET_ALL_SHOPS_BY_CATEGORY = "GET_ALL_SHOPS_BY_CATEGORY";
export const ADD_SHOP = "ADD_SHOP";
export const DELETE_SHOP = "DELETE_SHOP";
export const UPDATE_SHOP = "UPDATE_SHOP";
export const GET_SHOP_BY_ID = "GET_SHOP_BY_ID";

export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";

export const GET_ALL_ITEM_CLASSES = "GET_ALL_ITEM_CLASSES";
export const DELETE_ITEM_CLASS = "DELETE_ITEM_CLASS";
export const ADD_ITEM_CLASS = "ADD_ITEM_CLASS";
export const UPDATE_ITEM_CLASS = "UPDATE_ITEM_CLASS";

export const GET_ALL_ITEMS = "GET_ALL_ITEMS";
export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const UPDATE_ITEM = "UPDATE_ITEM";

export const GET_ALL_SHOP_ITEMS = "GET_ALL_SHOP_ITEMS";
export const DELETE_SHOP_ITEM = "DELETE_SHOP_ITEM";
export const ADD_SHOP_ITEM = "ADD_SHOP_ITEM";
export const UPDATE_SHOP_ITEM_QUANTITY = "UPDATE_SHOP_ITEM_QUANTITY";
export const UPDATE_SHOP_ITEM_PRICE = "UPDATE_SHOP_ITEM_PRICE";

export const GET_ALL_REQUISITIONS = "GET_ALL_REQUISITIONS";
export const UPDATE_REQUISITION = "UPDATE_REQUISITION";
export const ADD_REQUISITION = "ADD_REQUISITION";
export const DELETE_REQUISITION = "DELETE_REQUISITION";
export const UPDATE_REQUISITION_STATUS = "UPDATE_REQUISITION_STATUS";

export const GET_REQUISITIONS_BY_SHOP = "GET_REQUISITIONS_BY_SHOP";

export const SET_SELECTED_ORDER = "SET_SELECTED_ORDER";
